# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 03e8fcdd8a106d486067f9c9b0563ba1fb4af3d75c8dd5b28de8a79f5a505e24ca4849530d93392ab2bc4df2d54fe19a763eb52074d254d2b514b9bdc1754541

test:
  secret_key_base: 66060a318f2a4c5e6be29846d0459b069f3c041ff7905d1aff4d80f08bf865455d5b735334f1493337d1cba3bd6ac47c819c5346a98317f83309cbe5835f902d

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
